language: node_js

node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

script: 
  - yarn test -- --coverage --coverageDirectory ./coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)