const ROCK_SHAPE = 'ROCK';
const PAPER_SHAPE = 'PAPER';
const SCISSORS_SHAPE = 'SCISSORS';

const ALL_SHAPES = [ROCK_SHAPE, SCISSORS_SHAPE, PAPER_SHAPE];

const RULES = {
  [ROCK_SHAPE] : [SCISSORS_SHAPE],
  [PAPER_SHAPE] : [ROCK_SHAPE],
  [SCISSORS_SHAPE] : [PAPER_SHAPE],
}

export default {
  ALL_SHAPES,
  ROCK_SHAPE,
  PAPER_SHAPE,
  SCISSORS_SHAPE,
  RULES,
};